# Build settings
title: Desktop-Translucence # the main title
tagline: Hello! This is my project called Desktop-Translucence. It is basically a discord theme. # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  My project :>
theme: 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup

author:
  name:           'SillyAurora'
  url:            https://sillyaurora.github.io/desktop-translucence

paginate:         5

# Custom vars
version: 1.0

github:
  repo:           https://github.com/sillyaurora/desktop-translucence
