title: Desktop-Translucence Project
email: pazonneilcedrickvoid@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello! This is my project called Desktop-Translucence. It is basically a custom discord theme. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
discord_username: sillyaurora. 
github_username:  SillyAurora. 
youtube_username: medemonhunter

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
